services:
  - type: web
    name: billdeskpro-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql200.infinityfree.com
      - key: DB_USER
        value: if0_41875360
      - key: DB_PASSWORD
        value: zvPKoLNtdIA
      - key: DB_NAME
        value: if0_41875360_billing_system_db
      - key: JWT_SECRET
        value: billdeskpro_secret_key_2026
      - key: JWT_EXPIRE
        value: 8h